export const throwError = async (): Promise<never> => {
  throw new Error()
}
